### ISSUE TITLE
How to map this in normal mode?

### ISSUE THREAD

**Issue by jakubgs** [leafOfTree/vim-blink#1]
This is neat, but how do I map it to use it in normal mode? I tried:
```vim
nnoremap <expr> <C-j> blink#BlinkToEditPointNext()
nnoremap <expr> <C-k> blink#BlinkToEditPointPrev()
```
But it doesn't seem to work.

**Comment by leafOfTree** [comment]
Hi, I'm considering a refactor to support both INSERT and NORMAL mode. I'll let you know when updated.

**Comment by leafOfTree** [comment]
Hi, after updating, you can try
```vim
let g:blink_mapping_prev = '<c-k>'
let g:blink_mapping_next = '<c-j>'
let g:blink_enable_normal = 1
```
Or directly map
```vim
nnoremap<silent> <c-k> :call blink#BlinkToEditPoint("wb", 1)<cr>
nnoremap<silent> <c-j> :call blink#BlinkToEditPoint("w", 1)<cr>
```
Check https://github.com/leafOfTree/vim-blink#function

**Comment by jakubgs** [comment]
NICE. That works, thanks dude!

**Comment by jakubgs** [comment]
Although, now I see a separate issue, that the cursor appears right BEFORE the place I mark. Meaning:
If my rule for format `python` is ` *|def` then my cursor in normal mode moves to character before `def`:
```
   | def some_func():
```
But in insert mode it moves correctly:
```
    |def some_func():
```
Though that sounds like more of a pain to fix than just the mapping.

**Comment by leafOfTree** [comment]
Yeah, I've updated it so the cursor will on `d` of `def` in normal mode.
I was thinking about cases like `{|}` or `[|]`. The cursor is on `}` in normal mode. I feel like it should be on the left so I added one offset to put it on `{`. But it seems to cause more problems. Then I removed the offset.
I guess I'll get used to it. Otherwise, maybe I'll add another option to adjust it.

**Comment by jakubgs** [comment]
Thanks, appreciate it.
